### ISSUE TITLE
ok,thanks for rebuilding my code of instagram-python-scraper

### ISSUE THREAD

**Issue by luengwaiban** [SergioWagenleitner/instagram-scraper#2]
just do it your own way and I will stand away...

**Comment by SergioWagenleitner** [comment]
please look at my code and you see that I haven't rebuilt your code, we both rebuilt instagram-php-scraper, i used your proxy solution as well as I took yours and instagram-php-scrapers README.md as a blueprint. Please review my code then you  see that it is not rebuilt from your code. (besides we are all open source so copying and modifying wouldn't even be a bad thing) There are things I did completely different. If you cannot find those differences let me know I will show you.

**Comment by luengwaiban** [comment]
so I closed it.But still don't know why you grow fake stars .Can you explain that?

**Comment by luengwaiban** [comment]
@SergioWagenleitner can I have your email or what tool you use to chat?I have sth. to discuss....

**Comment by SergioWagenleitner** [comment]
You can contact me on Telegram, my username is realsirjoe

**Comment by luengwaiban** [comment]
@SergioWagenleitner can not.My account went wrong.can you contact me ? username is lueng seven

**Comment by SergioWagenleitner** [comment]
I cannot find lueng seven, when creating Telegram accounts you do not get usernames automatically, the name you type in on startup is just your display name, you need to go to settings and there you will find a section called create username or something like that

**Comment by luengwaiban** [comment]
ok done username lueng_seven  @SergioWagenleitner
